/**
 * The one cookie this product sets from a route handler, and the reader
 * that watches for it.
 *
 * It exists because a download is invisible to the page that started it.
 * `DownloadDocuments` is a plain anchor — the browser navigates, the ZIP
 * route answers, and no JavaScript is involved in any of it, which is
 * what keeps the download working with scripting off and lets the
 * `Content-Disposition` name the file. The cost of that design is that
 * nothing on the page can tell whether the archive is still being built
 * or has already landed in the downloads folder.
 *
 * A cookie closes that gap without giving the design up. Response
 * headers flush with the first byte of the body, so a cookie set on the
 * archive response arrives at exactly the moment the archive starts
 * arriving — which is the end of the wait the traveller is watching.
 *
 * Both halves are pure string functions, deliberately. The reading half
 * runs in a browser and the writing half runs on a server, and neither
 * one needs `document` or a `Response` to be tested.
 */

/** The name both halves agree on. */
export const ARCHIVE_READY_COOKIE = "archive_ready";

/**
 * One cookie's value out of a `document.cookie` string, or `null`.
 *
 * Split rather than matched with a regular expression, because the
 * obvious regular expression is the bug: `/archive_ready=([^;]*)/` also
 * matches inside `not_archive_ready=`, and a progress bar that clears on
 * an unrelated cookie is worse than one that never clears at all — it
 * says the file has arrived when it has not.
 */
export function readCookie(cookieString: string, name: string): string | null {
  for (const pair of cookieString.split(";")) {
    const separator = pair.indexOf("=");
    if (separator < 0) continue;
    if (pair.slice(0, separator).trim() === name) {
      return pair.slice(separator + 1).trim();
    }
  }
  return null;
}

/**
 * A ticket that cannot have been minted here. Anything outside this is
 * refused rather than escaped: the value is generated by
 * `crypto.randomUUID()` on the client and reflected back, so a ticket
 * that does not look like one is a caller trying something, not a
 * traveller with an unusual name.
 */
const TICKET = /^[a-z0-9-]{1,32}$/i;

/**
 * The `Set-Cookie` value the archive route answers with, or `null` if
 * the ticket is not one this product would have issued.
 *
 * `null` rather than a sanitised string. The ticket arrives in a query
 * parameter and lands in a response header, which is the hole
 * `archiveFilename` documents on the same route: a CRLF ends the header
 * and starts another of the caller's choosing, and a bare `;` forges an
 * attribute onto this cookie. Stripping those characters would answer a
 * forged ticket with a working cookie; refusing answers it with no
 * cookie, and the only casualty is a progress bar that runs its timeout.
 *
 * No `HttpOnly`, because the whole point is that a script reads it. That
 * is safe here in a way it would not be for a session: the value is a
 * nonce the client itself chose, it authorises nothing, and it is gone
 * in a minute.
 *
 * `SameSite=Lax` still arrives on the top-level navigation the download
 * is, and `Max-Age=60` keeps a cookie from one download out of the way
 * of the next.
 */
export function archiveReadyCookie(ticket: string, secure: boolean): string | null {
  if (!TICKET.test(ticket)) return null;

  const attributes = ["Path=/", "Max-Age=60", "SameSite=Lax"];
  if (secure) attributes.push("Secure");

  return `${ARCHIVE_READY_COOKIE}=${ticket}; ${attributes.join("; ")}`;
}
