/**
 * A real VisaList response, recorded verbatim — not invented, and not
 * trimmed.
 *
 * Captured 2026-09-02 from a single live call:
 *
 *   GET https://visa-list.p.rapidapi.com/api/public/visa_requirements/country/nigeria
 *   headers: x-rapidapi-key, x-rapidapi-host: visa-list.p.rapidapi.com
 *
 * The live response was 790 KB and carried **238 destinations** for a
 * Nigerian passport: 143 visa required, 56 e-visa, 28 visa free, 11 visa
 * on arrival.
 *
 * ## What is and is not the same as the API
 *
 * **Field-identical, row-subset.** The three top-level keys are the
 * vendor's own, and every row below is byte-identical to the row the API
 * returned — nothing renamed, reordered, defaulted or dropped. What is
 * reduced is the *number* of rows: 6 of 238 destinations, one
 * `nearbyCountries` entry of 5, and the whole `originCountry` block.
 *
 * The 6 were chosen so that between them they exercise **every field
 * the live response used anywhere across all 238 rows**:
 *
 * - United Kingdom — Visa Required, has `travelAdvice`, `passportPhotoUrl`,
 *   `visaStickerUrl`, `passportRenewalUrl` and a populated `exemptionVisa`
 * - Ghana — Visa Free, declaration form with no URL
 * - Rwanda — Visa on Arrival, carries `visaSchemeId`
 * - Ethiopia — E-visa, the only category left, and a declaration form
 *   whose URL is a reseller's
 * - Australia — the *only* row of 238 carrying `currencySymbol`
 * - Anguilla — a dependent territory, so it carries `parentCountryId`
 *
 * That completeness is the point. An earlier version kept a hand-picked
 * subset of *fields*, which made it useless as a contract: a schema
 * written against it would have silently accepted a payload it did not
 * understand — the exact failure `travelbuddy.ts` records in its own
 * envelope comment. `visalist.ts` parses this file in its tests, so the
 * schema is checked against the vendor's real shape.
 *
 * Note also what a recording *cannot* be: a type. `as const` over
 * heterogeneous rows infers a union in which any field some row omits
 * simply vanishes, so reading `sample.destinationCountry.currencySymbol`
 * does not compile. The schema in `visalist.ts` is the contract; this
 * file is the evidence it was written against.
 *
 * ## The finding this fixture exists to record
 *
 * The Phase 3 coverage plan is built on the claim that VisaList sells
 * "real checklists, tourism only", and gives its provider
 * `canLead: true`. **The payload contains no document checklist of any
 * kind.** Every field is an entry *rule* — category, duration, allowed
 * stay, notes, an exemption note, an eVisa link.
 * `documentDeclarationName` is the closest thing and it is a single
 * arrival or health declaration form, usually pointing at an iVisa
 * affiliate page, not a list of papers to gather.
 *
 * That makes VisaList the same shape as Travel Buddy: a contributor,
 * `canLead: false`. A provider that returns no documents must never open
 * a rule set — `adoptRuleSet` would materialise a checklist with zero
 * rows, so no upload slots, no completion score and no route to
 * submission.
 *
 * Kept in the repo so nobody pays for the call again: the Basic tier is
 * rate limited to one request an hour.
 */
export const VISALIST_NIGERIA_SAMPLE = {
  "nearbyCountries": [
    {
      "id": 24,
      "name": "Benin",
      "extraName": "",
      "alpha2Code": "BJ",
      "alpha3Code": "BEN",
      "slug": "benin",
      "imageUrl": "https://visalist.io/images/countries/benin/benin-af1695bc.moz.jpg",
      "gayRanking": 0,
      "gayScore": 0,
      "hasVisaPolicy": 0,
      "hasPassport": 0
    }
  ],
  "originCountry": {
    "id": 153,
    "name": "Nigeria",
    "extraName": "",
    "alpha2Code": "NG",
    "alpha3Code": "NGA",
    "numericCode": "566",
    "slug": "nigeria",
    "imageUrl": "https://visalist.io/images/countries/nigeria/nigeria-7e90fb53.moz.jpg",
    "capital": "Abuja",
    "ISDCode": "234",
    "currencyName": "Naira",
    "currencyCode": "NGN",
    "region": "Africa",
    "subregion": "Western Africa",
    "population": "186988000",
    "lat": "10",
    "lng": "8",
    "city": "Lagos",
    "cityLat": "6.5243793",
    "cityLng": "3.3792057",
    "area": "923768.0",
    "nearbyCountrySlugs": "cameroon,benin,niger,togo,equatorial-guinea",
    "timeZones": "UTC+01:00",
    "isIndependent": "Yes",
    "developmentStatus": "Developing",
    "languageCodes": "en",
    "languageNames": "English",
    "gayRanking": 152,
    "gayScore": -7,
    "countryVisaRanking": {
      "countryId": 153,
      "visaFree": 30,
      "visaOnArrival": 10,
      "eVisa": 48,
      "visaRequired": 150,
      "visaRefused": 0,
      "visaUnknown": 0,
      "visaEasyTotal": 40,
      "visaEasyOpen": 0,
      "ranking": 129
    },
    "visaProcessingUrl": "https://www.ivisa.com/apply-online/NG",
    "visaOnlineUrl": "https://www.ivisa.com/apply-online/NG",
    "documentDeclarationName": "Health Assessment",
    "hasVisaPolicy": 1,
    "hasPassport": 1,
    "createdAt": "2018-07-01T07:33:39Z",
    "updatedAt": "2026-06-29T05:23:22Z"
  },
  "visaRequirements": [
    {
      "id": 11788,
      "originCountryId": 153,
      "originCountry": null,
      "destinationCountryId": 223,
      "destinationCountry": {
        "id": 223,
        "name": "United Kingdom",
        "extraName": "UK",
        "alpha2Code": "GB",
        "alpha3Code": "GBR",
        "numericCode": "826",
        "slug": "united-kingdom",
        "imageUrl": "https://visalist.io/images/countries/united-kingdom/united-kingdom-809efadb.moz.jpg",
        "capital": "London",
        "ISDCode": "44",
        "currencyName": "Pound Sterling",
        "currencyCode": "GBP",
        "region": "Europe",
        "subregion": "Northern Europe",
        "population": "65110000",
        "lat": "54",
        "lng": "-2",
        "city": "London",
        "cityLat": "51.5073509",
        "cityLng": "-0.1277583",
        "area": "242900.0",
        "nearbyCountrySlugs": "isle-of-man,guernsey,jersey,ireland,belgium",
        "timeZones": "UTC+00:00",
        "isIndependent": "Yes",
        "developmentStatus": "Developed",
        "languageCodes": "en",
        "languageNames": "English",
        "gayRanking": 15,
        "gayScore": 9,
        "countryTemperature": {
          "id": 211,
          "countryId": 223,
          "jan": 3.548619,
          "feb": 3.5809588,
          "mar": 5.064868,
          "apr": 7.073514,
          "may": 10.003707,
          "jun": 12.657145,
          "jul": 14.396339,
          "aug": 14.28286,
          "sep": 12.310248,
          "oct": 9.353575,
          "nov": 5.982785,
          "dec": 4.198056,
          "createdAt": "2019-09-01T12:41:59Z",
          "updatedAt": "2021-12-09T23:30:18Z"
        },
        "travelAdvice": {
          "id": 95,
          "countryId": 223,
          "country": null,
          "adviceLevel": 3,
          "adviceDate": "2024-05-02T22:00:00Z",
          "advice": "We've reviewed our travel advice for the United Kingdom and continue to advise exercise a high degree of caution.\n\nWe advise:\nExercise a high degree of caution in the UK due to the threat of terrorism.",
          "adviceDescription": "Exercise a high degree of caution",
          "detailedAdvice": "",
          "sourceUrl": "https://www.smartraveller.gov.au/destinations/europe/united-kingdom",
          "createdAt": "2019-09-07T20:40:02Z",
          "updatedAt": "2024-06-13T22:30:21Z"
        },
        "visaProcessingUrl": "https://www.ivisa.com/apply-online/GB",
        "visaStickerUrl": "https://www.ivisa.com/apply-online/GB",
        "visaOnlineUrl": "https://www.ivisa.com/apply-online/GB",
        "embassyRegistraionUrl": "https://www.ivisa.com/embassy-registration",
        "passportRenewalUrl": "https://www.ivisa.com/passport-renewal/united-kingdom/application",
        "passportPhotoUrl": "https://www.ivisa.com/photos/order",
        "hasVisaPolicy": 1,
        "hasPassport": 1,
        "createdAt": "2018-07-01T07:33:39Z",
        "updatedAt": "2026-06-29T05:23:22Z"
      },
      "visaCategoryId": 4,
      "visaCategory": {
        "id": 4,
        "name": "Visa Required",
        "description": "Visa is required before travelling",
        "updatedAt": "2018-11-22T13:59:49Z"
      },
      "visaSubcategoryId": 0,
      "duration": "180 days",
      "stayDuration": "6 months",
      "notes": "Travelers need a visa to visit United Kingdom for Business or Tourism.::Travelers should check transit requirements for any other countries they transit through before arriving in the United Kingdom.:",
      "totalVotes": 1,
      "initialVotes": 7,
      "exemptionVisa": {
        "id": 27,
        "countryId": 223,
        "visaCategoryId": 1,
        "visaCategory": null,
        "duration": "24 hours",
        "applicableCountries": "",
        "exemptCountries": "",
        "details": "Visa exemption does not apply, but a 24-hour entry request is possible at London's Heathrow airport.\nTravel must be to or from Canada exclusively.\nArrival and departure must be by air.\nThe boarding pass for the onward flight is required.\nThe onward flight must be within 24 hours (same day or before midnight the next day).\nGranting the 24-hour entry is at the immigration officer's discretion.",
        "referenceUrl": "https://www.gov.uk/check-uk-visa/y/india/transit/somewhere_else/yes",
        "available": 1,
        "exemptionVisaCountries": null,
        "createdAt": "2019-01-04T11:35:01Z",
        "updatedAt": "2026-06-29T05:23:16Z"
      },
      "visaRequirementVote": null,
      "flightPrice": {
        "id": 279385,
        "originCountryId": 153,
        "destinationCountryId": 223,
        "minPrice": 775449,
        "currency": "NGN",
        "direct": 0,
        "outboundCarrierIds": "",
        "outboundCarrierNames": "",
        "outboundDate": "2024-07-15T00:00:00Z",
        "inboundCarrierIds": "",
        "inboundCarrierNames": "",
        "inboundDate": null,
        "quoteDateTime": "2024-06-03T19:24:00Z"
      },
      "userNotes": null,
      "embassies": null,
      "dualVisaRequirement": null,
      "slug": "nigeria-visa-requirements-for-uk-citizens",
      "website": "",
      "visaProcessingUrl": "",
      "visaProcessingAvailable": 1,
      "isETA": 0,
      "visaName": "visa required",
      "createdAt": "2018-07-01T07:33:39Z",
      "updatedAt": "2026-07-06T11:07:44Z"
    },
    {
      "id": 11671,
      "originCountryId": 153,
      "originCountry": null,
      "destinationCountryId": 79,
      "destinationCountry": {
        "id": 79,
        "name": "Ghana",
        "extraName": "",
        "alpha2Code": "GH",
        "alpha3Code": "GHA",
        "numericCode": "288",
        "slug": "ghana",
        "imageUrl": "https://visalist.io/images/countries/ghana/ghana-9ef20c73.moz.jpg",
        "capital": "Accra",
        "ISDCode": "233",
        "currencyName": "Ghana Cedi",
        "currencyCode": "GHS",
        "region": "Africa",
        "subregion": "Western Africa",
        "population": "27670174",
        "lat": "8",
        "lng": "-2",
        "city": "Accra",
        "cityLat": "5.6037168",
        "cityLng": "-0.1869644",
        "area": "238533.0",
        "nearbyCountrySlugs": "cote-divoire-ivory-coast,togo,benin,burkina-faso,liberia",
        "timeZones": "UTC+00:00",
        "isIndependent": "Yes",
        "developmentStatus": "Developing",
        "languageCodes": "en",
        "languageNames": "English",
        "gayRanking": 148,
        "gayScore": -7,
        "countryTemperature": {
          "id": 76,
          "countryId": 79,
          "jan": 26.858465,
          "feb": 28.940424,
          "mar": 29.48669,
          "apr": 29.184666,
          "may": 28.177439,
          "jun": 26.647793,
          "jul": 25.691345,
          "aug": 25.361197,
          "sep": 25.87995,
          "oct": 26.791925,
          "nov": 27.29367,
          "dec": 26.552588,
          "createdAt": "2019-09-01T12:41:27Z",
          "updatedAt": "2021-12-09T23:30:17Z"
        },
        "travelAdvice": {
          "id": 82,
          "countryId": 79,
          "country": null,
          "adviceLevel": 3,
          "adviceDate": "2024-03-04T23:00:00Z",
          "advice": "We continue to advise exercise a high degree of caution in Ghana. Higher levels apply in some areas. There's been an increase in reported incidents of banditry involving passenger buses travelling in the Upper West and Upper East regions resulting in injuries and deaths (see 'Safety').\n\nWe advise:\nExercise a high degree of caution in Ghana overall due to the threat of crime.\nHigher levels apply in some areas.",
          "adviceDescription": "Exercise a high degree of caution",
          "detailedAdvice": "",
          "sourceUrl": "https://www.smartraveller.gov.au/destinations/africa/ghana",
          "createdAt": "2019-09-07T20:40:02Z",
          "updatedAt": "2024-06-13T22:30:21Z"
        },
        "visaProcessingUrl": "https://www.ivisa.com/apply-online/GH",
        "visaOnlineUrl": "https://www.ivisa.com/apply-online/GH",
        "documentDeclarationName": "Health Declaration Form",
        "hasVisaPolicy": 1,
        "hasPassport": 1,
        "createdAt": "2018-07-01T07:33:39Z",
        "updatedAt": "2026-06-29T05:23:22Z"
      },
      "visaCategoryId": 1,
      "visaCategory": {
        "id": 1,
        "name": "Visa Free",
        "description": "Visa is not required for a certain period, or there is freedom of movement",
        "updatedAt": "2018-11-22T14:00:18Z"
      },
      "visaSubcategoryId": 0,
      "duration": "90 days",
      "stayDuration": "3 months",
      "notes": "Travelers do not need a visa for Business or Tourism stays up to 90 days. Travelers need a visa for longer stays.:",
      "totalVotes": 2,
      "initialVotes": 7,
      "exemptionVisa": {
        "id": 111,
        "countryId": 79,
        "visaCategoryId": 0,
        "visaCategory": null,
        "duration": "",
        "applicableCountries": "",
        "exemptCountries": "",
        "details": "",
        "referenceUrl": "",
        "available": 0,
        "exemptionVisaCountries": null,
        "createdAt": "2019-01-04T11:35:01Z",
        "updatedAt": "2026-06-29T05:23:16Z"
      },
      "visaRequirementVote": null,
      "flightPrice": {
        "id": 9720,
        "originCountryId": 153,
        "destinationCountryId": 79,
        "minPrice": 204504,
        "currency": "NGN",
        "direct": 1,
        "outboundCarrierIds": "",
        "outboundCarrierNames": "",
        "outboundDate": "2024-07-02T00:00:00Z",
        "inboundCarrierIds": "",
        "inboundCarrierNames": "",
        "inboundDate": null,
        "quoteDateTime": "2024-06-05T15:57:00Z"
      },
      "userNotes": null,
      "embassies": null,
      "dualVisaRequirement": null,
      "slug": "nigeria-visa-requirements-for-ghana-citizens",
      "website": "",
      "visaProcessingUrl": "",
      "visaProcessingAvailable": 0,
      "isETA": 0,
      "visaName": "visa free",
      "createdAt": "2018-07-01T07:33:39Z",
      "updatedAt": "2026-08-01T16:40:19Z"
    },
    {
      "id": 11748,
      "originCountryId": 153,
      "originCountry": null,
      "destinationCountryId": 175,
      "destinationCountry": {
        "id": 175,
        "name": "Rwanda",
        "extraName": "",
        "alpha2Code": "RW",
        "alpha3Code": "RWA",
        "numericCode": "646",
        "slug": "rwanda",
        "imageUrl": "https://visalist.io/images/countries/rwanda/rwanda-c44e8bb0.moz.jpg",
        "capital": "Kigali",
        "ISDCode": "250",
        "currencyName": "Rwanda Franc",
        "currencyCode": "RWF",
        "region": "Africa",
        "subregion": "Eastern Africa",
        "population": "11553188",
        "lat": "-2",
        "lng": "30",
        "city": "Kigali",
        "cityLat": "-1.9705786",
        "cityLng": "30.1044288",
        "area": "26338.0",
        "nearbyCountrySlugs": "burundi,uganda,democratic-republic-of-congo,tanzania,kenya",
        "visaSchemeId": 3,
        "timeZones": "UTC+02:00",
        "isIndependent": "Yes",
        "developmentStatus": "Least Developed",
        "languageCodes": "rw,en,fr",
        "languageNames": "Kinyarwanda,English,French",
        "gayRanking": 111,
        "gayScore": -4,
        "countryTemperature": {
          "id": 169,
          "countryId": 175,
          "jan": 18.875334,
          "feb": 19.144474,
          "mar": 19.03616,
          "apr": 18.94241,
          "may": 18.74241,
          "jun": 18.389732,
          "jul": 18.290514,
          "aug": 19.000614,
          "sep": 19.117746,
          "oct": 18.982756,
          "nov": 18.743303,
          "dec": 18.73192,
          "createdAt": "2019-09-01T12:41:50Z",
          "updatedAt": "2021-11-09T23:30:18Z"
        },
        "travelAdvice": {
          "id": 19,
          "countryId": 175,
          "country": null,
          "adviceLevel": 2,
          "adviceDate": "2024-05-29T22:00:00Z",
          "advice": "We continue to advise exercise normal safety precautions in Rwanda overall. Higher levels apply in some areas.  The land border with Burundi is currently closed (see 'Travel').\n\nWe advise:\nExercise normal safety precautions in Rwanda. \nHigher levels apply in some areas.",
          "adviceDescription": "Exercise normal safety precautions",
          "detailedAdvice": "",
          "sourceUrl": "https://www.smartraveller.gov.au/destinations/africa/rwanda",
          "createdAt": "2019-09-07T20:40:02Z",
          "updatedAt": "2024-06-13T22:30:21Z"
        },
        "visaProcessingUrl": "https://www.ivisa.com/apply-online/RW",
        "visaStickerUrl": "https://www.visagov.com/en/rwa-visa-for-rwanda#a_aid=visalistio&a_bid=25864697",
        "visaOnlineUrl": "https://www.ivisa.com/apply-online/RW",
        "documentDeclarationName": "Passenger Locator Form",
        "hasVisaPolicy": 1,
        "hasPassport": 1,
        "createdAt": "2018-07-01T07:33:39Z",
        "updatedAt": "2026-06-29T05:23:22Z"
      },
      "visaCategoryId": 2,
      "visaCategory": {
        "id": 2,
        "name": "Visa on Arrival",
        "description": "Visa needs to be taken on arrival at the port of entry",
        "updatedAt": "2018-12-20T08:56:35Z"
      },
      "visaSubcategoryId": 0,
      "duration": "30 days",
      "stayDuration": "1 month",
      "notes": "Travelers need a visa to visit Rwanda for Business or Tourism. ::Travelers can get a free-of-charge visa on arrival in Rwanda at the port of entry, such as an international airport or border crossing.:",
      "totalVotes": 1,
      "initialVotes": 1,
      "exemptionVisa": {
        "id": 188,
        "countryId": 175,
        "visaCategoryId": 0,
        "visaCategory": null,
        "duration": "",
        "applicableCountries": "",
        "exemptCountries": "",
        "details": "",
        "referenceUrl": "",
        "available": 0,
        "exemptionVisaCountries": null,
        "createdAt": "2019-01-04T11:35:01Z",
        "updatedAt": "2026-06-29T05:23:16Z"
      },
      "visaRequirementVote": null,
      "flightPrice": {
        "id": 9721,
        "originCountryId": 153,
        "destinationCountryId": 175,
        "minPrice": 918090,
        "currency": "NGN",
        "direct": 1,
        "outboundCarrierIds": "",
        "outboundCarrierNames": "",
        "outboundDate": "2024-07-16T00:00:00Z",
        "inboundCarrierIds": "",
        "inboundCarrierNames": "",
        "inboundDate": null,
        "quoteDateTime": "2024-06-08T19:45:00Z"
      },
      "userNotes": null,
      "embassies": null,
      "dualVisaRequirement": null,
      "slug": "nigeria-visa-requirements-for-rwanda-citizens",
      "website": "",
      "visaProcessingUrl": "",
      "visaProcessingAvailable": 0,
      "isETA": 0,
      "visaName": "visa on arrival",
      "createdAt": "2018-07-01T07:33:39Z",
      "updatedAt": "2026-07-06T11:07:44Z"
    },
    {
      "id": 11663,
      "originCountryId": 153,
      "originCountry": null,
      "destinationCountryId": 67,
      "destinationCountry": {
        "id": 67,
        "name": "Ethiopia",
        "extraName": "",
        "alpha2Code": "ET",
        "alpha3Code": "ETH",
        "numericCode": "231",
        "slug": "ethiopia",
        "imageUrl": "https://visalist.io/images/countries/ethiopia/ethiopia-fde96306.moz.jpg",
        "capital": "Addis Ababa",
        "ISDCode": "251",
        "currencyName": "Ethiopian Birr",
        "currencyCode": "ETB",
        "region": "Africa",
        "subregion": "Eastern Africa",
        "population": "92206005",
        "lat": "8",
        "lng": "38",
        "city": "Addis Ababa",
        "cityLat": "8.9806034",
        "cityLng": "38.7577605",
        "area": "1104300.0",
        "nearbyCountrySlugs": "djibouti,kenya,eritrea,south-sudan,uganda",
        "timeZones": "UTC+03:00",
        "isIndependent": "Yes",
        "developmentStatus": "Least Developed",
        "languageCodes": "am",
        "languageNames": "Amharic",
        "gayRanking": 160,
        "gayScore": -8,
        "countryTemperature": {
          "id": 64,
          "countryId": 67,
          "jan": 21.726053,
          "feb": 22.867867,
          "mar": 24.000721,
          "apr": 24.447376,
          "may": 24.336813,
          "jun": 23.93457,
          "jul": 23.004854,
          "aug": 22.730026,
          "sep": 23.197289,
          "oct": 22.739773,
          "nov": 21.94503,
          "dec": 21.400387,
          "createdAt": "2019-09-01T12:41:24Z",
          "updatedAt": "2021-12-09T23:30:17Z"
        },
        "travelAdvice": {
          "id": 117,
          "countryId": 67,
          "country": null,
          "adviceLevel": 4,
          "adviceDate": "2024-05-06T22:00:00Z",
          "advice": "We've reviewed our advice and continue to advise reconsider your need to travel to Ethiopia overall due to the risk of civil unrest and the threat of armed conflict.  We continue to advise do not travel to Amhara Regional State due to the security situation. We also advise do not travel to a number of other locations in Ethiopia. A state of emergency remains in place. Petty crime is common in Addis Ababa. Remain alert.\nWe advise:\nReconsider your need to travel to Ethiopia overall due to the risk of civil unrest and the threat of armed conflict.\nOther levels apply in some areas.",
          "adviceDescription": "Reconsider your need to travel",
          "detailedAdvice": "",
          "sourceUrl": "https://www.smartraveller.gov.au/destinations/africa/ethiopia",
          "createdAt": "2019-09-07T20:40:02Z",
          "updatedAt": "2024-06-13T22:30:21Z"
        },
        "visaProcessingUrl": "https://www.ivisa.com/apply-online/ethiopia",
        "visaOnlineUrl": "https://www.ivisa.com/apply-online/ethiopia",
        "documentDeclarationUrl": "https://www.ivisa.com/apply-online/ethiopia",
        "documentDeclarationName": "Traveler's Health Declaration",
        "hasVisaPolicy": 1,
        "hasPassport": 1,
        "createdAt": "2018-07-01T07:33:39Z",
        "updatedAt": "2026-06-29T05:23:22Z"
      },
      "visaCategoryId": 3,
      "visaCategory": {
        "id": 3,
        "name": "E-visa",
        "description": "Visa can be taken online before travel like Online Visa or Electronic Travel Authority",
        "updatedAt": "2018-12-20T08:56:42Z"
      },
      "visaSubcategoryId": 0,
      "duration": "90 days",
      "stayDuration": "3 months",
      "notes": "Travelers need a visa to visit Ethiopia for Tourism.::An Ethiopian eVisa is the fastest way to obtain a visa. Travelers can apply online. Once approved, travelers receive their eVisa confirmation electronically.::A valid visa is required to board the flight. If the visa is expired or doesn’t match the traveler’s passport information, travelers will not be able to board their flight.::Only travelers born in Ethiopia with an Ethiopian Origin ID Card can obtain a visa on arrival at Addis Ababa Bole International Airport (ADD). This also applies to travelers under the age of 16 accompanying travelers born in Ethiopia with an Ethiopian Origin ID Card.:",
      "totalVotes": 2,
      "initialVotes": 4,
      "exemptionVisa": {
        "id": 100,
        "countryId": 67,
        "visaCategoryId": 0,
        "visaCategory": null,
        "duration": "",
        "applicableCountries": "",
        "exemptCountries": "",
        "details": "",
        "referenceUrl": "",
        "available": 0,
        "exemptionVisaCountries": null,
        "createdAt": "2019-01-04T11:35:01Z",
        "updatedAt": "2026-06-29T05:23:16Z"
      },
      "visaRequirementVote": null,
      "flightPrice": {
        "id": 9799,
        "originCountryId": 153,
        "destinationCountryId": 67,
        "minPrice": 1126340,
        "currency": "NGN",
        "direct": 1,
        "outboundCarrierIds": "",
        "outboundCarrierNames": "",
        "outboundDate": "2024-07-30T00:00:00Z",
        "inboundCarrierIds": "",
        "inboundCarrierNames": "",
        "inboundDate": null,
        "quoteDateTime": "2024-06-07T17:28:00Z"
      },
      "userNotes": null,
      "embassies": null,
      "dualVisaRequirement": null,
      "slug": "nigeria-visa-requirements-for-ethiopia-citizens",
      "website": "",
      "visaProcessingUrl": "",
      "visaProcessingAvailable": 1,
      "isETA": 0,
      "visaName": "e visa",
      "createdAt": "2018-07-01T07:33:39Z",
      "updatedAt": "2026-07-06T11:07:44Z"
    },
    {
      "id": 11614,
      "originCountryId": 153,
      "originCountry": null,
      "destinationCountryId": 14,
      "destinationCountry": {
        "id": 14,
        "name": "Australia",
        "extraName": "",
        "alpha2Code": "AU",
        "alpha3Code": "AUS",
        "numericCode": "36",
        "slug": "australia",
        "imageUrl": "https://visalist.io/images/countries/australia/australia-8b200988.moz.jpg",
        "capital": "Canberra",
        "ISDCode": "61",
        "currencyName": "Australian Dollar",
        "currencyCode": "AUD",
        "currencySymbol": "$",
        "region": "Oceania",
        "subregion": "Australia and New Zealand",
        "population": "24117360",
        "lat": "-27",
        "lng": "133",
        "city": "Sydney",
        "cityLat": "-33.8688197",
        "cityLng": "151.2092955",
        "area": "7692024.0",
        "nearbyCountrySlugs": "timor-leste,papua-new-guinea,indonesia,solomon-islands,new-caledonia",
        "timeZones": "UTC+08:00,UTC+08:45,UTC+09:30,UTC+10:00,UTC+10:30,UTC+11:30",
        "isIndependent": "Yes",
        "developmentStatus": "Developed",
        "languageCodes": "en",
        "languageNames": "English",
        "gayRanking": 30,
        "gayScore": 6,
        "countryTemperature": {
          "id": 12,
          "countryId": 14,
          "jan": 27.395493,
          "feb": 26.850956,
          "mar": 25.066504,
          "apr": 21.66571,
          "may": 17.81826,
          "jun": 14.896624,
          "jul": 14.075693,
          "aug": 15.757487,
          "sep": 18.887165,
          "oct": 22.17104,
          "nov": 24.850462,
          "dec": 26.560062,
          "createdAt": "2019-09-01T12:41:12Z",
          "updatedAt": "2021-12-09T23:30:17Z"
        },
        "travelAdvice": {
          "id": 178,
          "countryId": 14,
          "country": null,
          "adviceLevel": 2,
          "adviceDate": "2019-09-12T04:19:33Z",
          "advice": "",
          "adviceDescription": "Exercise normal safety precautions",
          "detailedAdvice": "",
          "sourceUrl": "",
          "createdAt": "2019-09-07T20:40:02Z",
          "updatedAt": "2023-06-07T18:33:59Z"
        },
        "visaProcessingUrl": "https://www.ivisa.com/apply-online/australia",
        "visaOnlineUrl": "https://www.ivisa.com/apply-online/australia",
        "documentDeclarationUrl": "https://www.ivisa.com/apply-online/australia",
        "documentDeclarationName": "Travel Declaration",
        "embassyRegistraionUrl": "https://www.ivisa.com/embassy-registration",
        "passportPhotoUrl": "https://www.ivisa.com/photos/order",
        "hasVisaPolicy": 1,
        "hasPassport": 1,
        "createdAt": "2018-07-01T07:33:39Z",
        "updatedAt": "2026-06-29T05:23:22Z"
      },
      "visaCategoryId": 3,
      "visaCategory": {
        "id": 3,
        "name": "E-visa",
        "description": "Visa can be taken online before travel like Online Visa or Electronic Travel Authority",
        "updatedAt": "2018-12-20T08:56:42Z"
      },
      "visaSubcategoryId": 0,
      "duration": "90 days",
      "stayDuration": "3 months",
      "notes": "Travelers need a visa to visit Australia for Business or Tourism. An Australian eVisa is the fastest way to obtain a visa. Travelers can apply online. Once approved, travelers receive their eVisa confirmation electronically.:",
      "totalVotes": 29,
      "initialVotes": 6,
      "exemptionVisa": {
        "id": 64,
        "countryId": 14,
        "visaCategoryId": 0,
        "visaCategory": null,
        "duration": "",
        "applicableCountries": "",
        "exemptCountries": "",
        "details": "",
        "referenceUrl": "",
        "available": 0,
        "exemptionVisaCountries": null,
        "createdAt": "2019-01-04T11:35:01Z",
        "updatedAt": "2026-06-29T05:23:16Z"
      },
      "visaRequirementVote": null,
      "flightPrice": {
        "id": 9827,
        "originCountryId": 153,
        "destinationCountryId": 14,
        "minPrice": 1370457,
        "currency": "NGN",
        "direct": 0,
        "outboundCarrierIds": "",
        "outboundCarrierNames": "",
        "outboundDate": "2024-07-07T00:00:00Z",
        "inboundCarrierIds": "",
        "inboundCarrierNames": "",
        "inboundDate": null,
        "quoteDateTime": "2024-06-07T18:28:00Z"
      },
      "userNotes": null,
      "embassies": null,
      "dualVisaRequirement": null,
      "slug": "nigeria-visa-requirements-for-australia-citizens",
      "website": "",
      "visaProcessingUrl": "",
      "visaProcessingAvailable": 1,
      "isETA": 0,
      "visaName": "e visa",
      "createdAt": "2018-07-01T07:33:39Z",
      "updatedAt": "2026-07-06T11:07:44Z"
    },
    {
      "id": 11813,
      "originCountryId": 153,
      "originCountry": null,
      "destinationCountryId": 8,
      "destinationCountry": {
        "id": 8,
        "name": "Anguilla",
        "extraName": "",
        "alpha2Code": "AI",
        "alpha3Code": "AIA",
        "numericCode": "660",
        "slug": "anguilla",
        "imageUrl": "https://visalist.io/images/countries/anguilla/anguilla-6e84c423.moz.jpg",
        "capital": "The Valley",
        "ISDCode": "1264",
        "currencyName": "East Caribbean Dollar",
        "currencyCode": "XCD",
        "region": "North America",
        "subregion": "Caribbean",
        "population": "13452",
        "lat": "18.25",
        "lng": "-63.16666666",
        "city": "The Valley",
        "cityLat": "18.2148129",
        "cityLng": "-63.0574406",
        "area": "91.0",
        "nearbyCountrySlugs": "sint-maarten-dutch-part,saint-barthlemy,saint-martin-french-part,saint-kitts-and-nevis,british-virgin-islands",
        "parentCountryId": 223,
        "timeZones": "UTC-04:00",
        "isIndependent": "Territory of UK",
        "developmentStatus": "Developing",
        "languageCodes": "en",
        "languageNames": "English",
        "gayRanking": 0,
        "gayScore": 0,
        "countryTemperature": {
          "id": 7,
          "countryId": 8,
          "jan": 23.97156,
          "feb": 23.916513,
          "mar": 24.29266,
          "apr": 24.608257,
          "may": 25.431192,
          "jun": 25.862385,
          "jul": 26.127523,
          "aug": 26.537617,
          "sep": 26.523853,
          "oct": 26.255962,
          "nov": 25.743118,
          "dec": 24.744953,
          "createdAt": "2019-09-01T12:41:10Z",
          "updatedAt": "2021-12-09T23:30:17Z"
        },
        "visaProcessingUrl": "https://www.ivisa.com/apply-online/AI",
        "visaStickerUrl": "https://www.ivisa.com/apply-online/GB",
        "visaOnlineUrl": "https://www.ivisa.com/apply-online/GB",
        "hasVisaPolicy": 1,
        "hasPassport": 1,
        "createdAt": "2018-07-01T07:33:39Z",
        "updatedAt": "2026-06-29T05:23:22Z"
      },
      "visaCategoryId": 3,
      "visaCategory": {
        "id": 3,
        "name": "E-visa",
        "description": "Visa can be taken online before travel like Online Visa or Electronic Travel Authority",
        "updatedAt": "2018-12-20T08:56:42Z"
      },
      "visaSubcategoryId": 0,
      "duration": "90 days",
      "stayDuration": "3 months",
      "notes": "Travelers need a visa to visit Anguilla for Business or Tourism. An Anguilla eVisa is the fastest way to obtain a visa. Travelers can apply online. Once approved, travelers receive their eVisa confirmation electronically.:",
      "totalVotes": 0,
      "initialVotes": 8,
      "exemptionVisa": {
        "id": 56,
        "countryId": 8,
        "visaCategoryId": 1,
        "visaCategory": null,
        "duration": "90 days",
        "applicableCountries": "",
        "exemptCountries": "",
        "details": "",
        "referenceUrl": "https://ivisitanguilla.com/entry-requirements/",
        "available": 1,
        "exemptionVisaCountries": null,
        "createdAt": "2019-01-04T11:35:01Z",
        "updatedAt": "2026-06-29T05:23:16Z"
      },
      "visaRequirementVote": null,
      "userNotes": null,
      "embassies": null,
      "dualVisaRequirement": null,
      "slug": "nigeria-visa-requirements-for-anguilla-citizens",
      "website": "",
      "visaProcessingUrl": "",
      "visaProcessingAvailable": -1,
      "isETA": 0,
      "visaName": "e visa",
      "createdAt": "2018-07-01T07:33:39Z",
      "updatedAt": "2026-07-06T11:07:44Z"
    }
  ]
} as const;

/**
 * Every key observed across all 238 entries of the live response.
 * `visalist.test.ts` asserts the schema names nothing outside these, and
 * that the recorded rows above exercise all of them.
 */
export const VISALIST_OBSERVED_ENTRY_KEYS = [
  "createdAt",
  "destinationCountry",
  "destinationCountryId",
  "dualVisaRequirement",
  "duration",
  "embassies",
  "exemptionVisa",
  "flightPrice",
  "id",
  "initialVotes",
  "isETA",
  "notes",
  "originCountry",
  "originCountryId",
  "slug",
  "stayDuration",
  "totalVotes",
  "updatedAt",
  "userNotes",
  "visaCategory",
  "visaCategoryId",
  "visaName",
  "visaProcessingAvailable",
  "visaProcessingUrl",
  "visaRequirementVote",
  "visaSubcategoryId",
  "website"
] as const;

export const VISALIST_OBSERVED_COUNTRY_KEYS = [
  "ISDCode",
  "alpha2Code",
  "alpha3Code",
  "area",
  "capital",
  "city",
  "cityLat",
  "cityLng",
  "countryTemperature",
  "createdAt",
  "currencyCode",
  "currencyName",
  "currencySymbol",
  "developmentStatus",
  "documentDeclarationName",
  "documentDeclarationUrl",
  "embassyRegistraionUrl",
  "extraName",
  "gayRanking",
  "gayScore",
  "hasPassport",
  "hasVisaPolicy",
  "id",
  "imageUrl",
  "isIndependent",
  "languageCodes",
  "languageNames",
  "lat",
  "lng",
  "name",
  "nearbyCountrySlugs",
  "numericCode",
  "parentCountryId",
  "passportPhotoUrl",
  "passportRenewalUrl",
  "population",
  "region",
  "slug",
  "subregion",
  "timeZones",
  "travelAdvice",
  "updatedAt",
  "visaOnlineUrl",
  "visaProcessingUrl",
  "visaSchemeId",
  "visaStickerUrl"
] as const;

/**
 * The delimiter VisaList uses inside `notes`: entries are separated by
 * `::` and each one ends with a bare `:`. Recorded because it is the
 * sort of undocumented detail that is expensive to rediscover.
 */
export const VISALIST_NOTE_SEPARATOR = "::";
